# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zipbomb < Formula
  desc "Tool that creates different types of zip bombs"
  homepage "https://github.com/hupe1980/zipbomb"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hupe1980/zipbomb/releases/download/v0.0.5/zipbomb_Darwin_x86_64.tar.gz"
      sha256 "e513c4806fd9de55d21c80ac5dc6144559603dc7e98fa3f97bf271bf5f24d194"

      def install
        bin.install "zipbomb"
        bash_completion.install "completions/zipbomb.bash" => "zipbomb"
        zsh_completion.install "completions/zipbomb.zsh" => "_zipbomb"
        fish_completion.install "completions/zipbomb.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hupe1980/zipbomb/releases/download/v0.0.5/zipbomb_Darwin_arm64.tar.gz"
      sha256 "7798ffb009652bcf82808c8eb6981115fdc1fd64a1434d8720551dcf0d3d6a97"

      def install
        bin.install "zipbomb"
        bash_completion.install "completions/zipbomb.bash" => "zipbomb"
        zsh_completion.install "completions/zipbomb.zsh" => "_zipbomb"
        fish_completion.install "completions/zipbomb.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hupe1980/zipbomb/releases/download/v0.0.5/zipbomb_Linux_armv6.tar.gz"
      sha256 "fe82e559051d5cfd7683dcfe36e51cd7af1ef09f212610d801575db7b056c547"

      def install
        bin.install "zipbomb"
        bash_completion.install "completions/zipbomb.bash" => "zipbomb"
        zsh_completion.install "completions/zipbomb.zsh" => "_zipbomb"
        fish_completion.install "completions/zipbomb.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hupe1980/zipbomb/releases/download/v0.0.5/zipbomb_Linux_arm64.tar.gz"
      sha256 "de2cfe686c76e2a1dbd625d915d37e111eaba35782a1da29becfc5bc9d7fbb21"

      def install
        bin.install "zipbomb"
        bash_completion.install "completions/zipbomb.bash" => "zipbomb"
        zsh_completion.install "completions/zipbomb.zsh" => "_zipbomb"
        fish_completion.install "completions/zipbomb.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hupe1980/zipbomb/releases/download/v0.0.5/zipbomb_Linux_x86_64.tar.gz"
      sha256 "cff323e038d8d928a01ee0f7f92d9fc18aa94ea62b782fe7801d67e5c9a7b4be"

      def install
        bin.install "zipbomb"
        bash_completion.install "completions/zipbomb.bash" => "zipbomb"
        zsh_completion.install "completions/zipbomb.zsh" => "_zipbomb"
        fish_completion.install "completions/zipbomb.fish"
      end
    end
  end

  test do
    system "#{bin}/zipbomb -v"
  end
end
