# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zipbomb < Formula
  desc "Tool that creates zip bombs"
  homepage "https://github.com/hupe1980/zipbomb"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hupe1980/zipbomb/releases/download/v0.0.1/zipbomb_Darwin_x86_64.tar.gz"
      sha256 "75624db5a219ce8129e551d760c3bf730a2961cbb0cf3827efa51923bae63d7b"

      def install
        bin.install "zipbomb"
        bash_completion.install "completions/zipbomb.bash" => "zipbomb"
        zsh_completion.install "completions/zipbomb.zsh" => "_zipbomb"
        fish_completion.install "completions/zipbomb.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hupe1980/zipbomb/releases/download/v0.0.1/zipbomb_Darwin_arm64.tar.gz"
      sha256 "ebd3c86439ce5c24c12e794c85989af2448c47d1e7e67e0be9d1d5411eddb283"

      def install
        bin.install "zipbomb"
        bash_completion.install "completions/zipbomb.bash" => "zipbomb"
        zsh_completion.install "completions/zipbomb.zsh" => "_zipbomb"
        fish_completion.install "completions/zipbomb.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/hupe1980/zipbomb/releases/download/v0.0.1/zipbomb_Linux_armv6.tar.gz"
      sha256 "ac2719acf27aa050adf04367241c4bd324c6e2459ec4f7d622da59275ead2dd2"

      def install
        bin.install "zipbomb"
        bash_completion.install "completions/zipbomb.bash" => "zipbomb"
        zsh_completion.install "completions/zipbomb.zsh" => "_zipbomb"
        fish_completion.install "completions/zipbomb.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hupe1980/zipbomb/releases/download/v0.0.1/zipbomb_Linux_x86_64.tar.gz"
      sha256 "702c175c2ed53fd5db5ad327dbc7b17068aaf11ce895927ef571cb94d940859a"

      def install
        bin.install "zipbomb"
        bash_completion.install "completions/zipbomb.bash" => "zipbomb"
        zsh_completion.install "completions/zipbomb.zsh" => "_zipbomb"
        fish_completion.install "completions/zipbomb.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hupe1980/zipbomb/releases/download/v0.0.1/zipbomb_Linux_arm64.tar.gz"
      sha256 "450ab94b39111710ea4b271f08ee8a1f3874481326c3ef43dce4613dc1dd109f"

      def install
        bin.install "zipbomb"
        bash_completion.install "completions/zipbomb.bash" => "zipbomb"
        zsh_completion.install "completions/zipbomb.zsh" => "_zipbomb"
        fish_completion.install "completions/zipbomb.fish"
      end
    end
  end

  test do
    system "#{bin}/zipbomb -v"
  end
end
